import {
  Code2,
  ShoppingBag,
  Search,
  Bot,
  GitMerge,
  LayoutDashboard,
  LayoutTemplate,
  LayoutPanelTop,
  Server,
  Contact,
  Kanban,
  Workflow,
  Megaphone,
  Target,
  BarChart3,
  PenTool,
  TrendingUp,
  Clapperboard,
  Puzzle,
  Sparkles,
  Gauge,
  Compass,
  HeartPulse,
  Sprout,
  Briefcase,
  Utensils,
  Flag,
  Repeat,
  Layers,
  type LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  "code-2": Code2,
  "shopping-bag": ShoppingBag,
  search: Search,
  bot: Bot,
  "git-merge": GitMerge,
  "layout-dashboard": LayoutDashboard,
  "layout-template": LayoutTemplate,
  "layout-panel-top": LayoutPanelTop,
  server: Server,
  contact: Contact,
  kanban: Kanban,
  workflow: Workflow,
  megaphone: Megaphone,
  target: Target,
  "bar-chart-3": BarChart3,
  "pen-tool": PenTool,
  "trending-up": TrendingUp,
  clapperboard: Clapperboard,
  puzzle: Puzzle,
  sparkles: Sparkles,
  gauge: Gauge,
  compass: Compass,
  "heart-pulse": HeartPulse,
  sprout: Sprout,
  briefcase: Briefcase,
  utensils: Utensils,
  flag: Flag,
  repeat: Repeat,
  layers: Layers,
};
